##### SELECT ARCHITECTURE#######################
#SUPER COMPUTER
arc=mod_mpi.o
compiler=f90jxflat -Umpi -Uomp
#compiler=f90jx -Umpi -Uomp
#compiler=f90jx -Umpi
#compiler=f90jx -Umpi -Uomp -xert,cvr
##### END SELECT ARCHITECTURE###################

