#chemlib
LU.o: LU.f90
	$(compiler) -c $<
mod_chem.o:  mod_chem.f90
	$(compiler) -c $<
func_chem.o:  func_chem.f90 mod_chem.o
	$(compiler) -c $<
sub_chem.o:  sub_chem.f90  func_chem.o LU.o mod_chem.o
	$(compiler) -c $<
